src/leap/mail/adaptors/soledad.py
src/leap/mail/imap/mailbox.py
src/leap/mail/mail.py
src/leap/mail/mailbox_indexer.py
src/leap/mail/sync_hooks.py

- Add errback handling to catch properly errors that were not allowing
the complete insertion of the parts for a given message. Fixes blank
attachments and moving of messages to different folders.
- Force overwritting of mdoc when it is a copy. This was avoiding a
message to be copied back to a folder from where it already had been
copied to another (since the mdoc was already existing there, with the
same doc_id, which was forbidding the creation of the new one).
This case also needs special care in the indexer, since we have to
delete the old hash entry first.
Closes: #7178, #7158

[bug] fixes for display attachments and move between folders

---

src/leap/mail/adaptors/soledad.py

in a previous commit, there was a bug inserted in which a key lookup was
being made unconditionally, even when the pending_insert_docs was None.
Releases: 0.4.0

[bug] avoid KeyError on pending_insert_docs lookup

---

src/leap/mail/adaptors/soledad.py
src/leap/mail/imap/mailbox.py
src/leap/mail/mail.py

in a previous refactor, we decoupled the incoming mail service from the
IMAP layer. However, this left the IMAPMailbox unable to react to
changes in the underlying collection when a new message is inserted.
in this commit, we add a Listener mechanism to the collection itself, so
that IMAPMailbox (and any other object that uses it) can subscribe to
changes on the number of messages of the collection.
Resolves: #7191
Releases: 0.4.0

[bug] allow mailbox to be notified of collection changes

---

pkg/requirements-leap.pip
pkg/requirements.pip
pkg/utils.py
setup.py

this is part of a process to make the setup of the development mode less
troublesome. from now on, setting up a virtualenv in pure development
mode will be as easy as telling pip to just install the external
dependencies::
pip install -r pkg/requirements.pip
and traversing all the leap repos for the needed leap dependencies doing::
python setup.py develop
- Related: #7288

[pkg] separate leap requirements

---

pkg/requirements-latest.pip
src/leap/mail/adaptors/tests/test_soledad_adaptor.py
src/leap/mail/imap/tests/test_imap_store_fetch.py
src/leap/mail/tests/test_mail.py

Hey, I changed the leap mail tests to make sure it skips not implemented behavior instead of calling .fail() . This way you still have a reminder that you have to implement that, but it doesn't break the tests.
IMAP Mixin was being initialized without handling, but it returns a deferred, the deferred was being collected before it was run, and that was breaking the imap tests (that depended on the result of that deferred). The IMAP fetch tests still need to be fixed because they are outdated and they can't handle callbacks (some of the class methods changed and the part of the test still expects synchronous code)

Skip instead of fail on not implemented behavior

---

src/leap/mail/adaptors/models.py
src/leap/mail/adaptors/tests/test_soledad_adaptor.py
src/leap/mail/walk.py

[bug] Fix missing _normailize_dict in DocumentWrapper constructor.
In the constructor values already is normalized (i.e. with underscores),
while kwargs contains items that are not normalized (i.e. with dashes).
Joining the dicts resulted in two entries that only differed by dash or
underscores. The setattr then set the value that occurred later in
items, thereby sometimes overriding the correct value with the default
one.
[bug] Fix typo in content-transfer-encoding in walk.py.
The get_raw_docs method accesses header field content-transfer-encoding
using the string 'content-transfer-type' so the raw doc dict always ends
up with that value set to empty string.

Fix two bugs when converting multipart mails to ContentDocWrappers

---

src/leap/mail/imap/tests/getmail

So now it:
- Accepts credentials in a file pointed by environment variable.
- Allows to specify the mailbox to select as a command line flag.
- Allows to select a given message by subject.
For example:
BITMASK_CREDENTIALS=/tmp/bm.secrets ./getmail --mailbox INBOX --subject
'test mail
The two flags are case-insensitive.
This is intended to be used as a helper in end-to-end tests.
Getting a message by subject it's suboptimal, but I think it's good
enough for our testing purposes right now.
Related: #7427

[feature] improve getmail utility

---

src/leap/mail/incoming/service.py
src/leap/mail/incoming/tests/test_incoming_mail.py

We are doing so so that we can know later if that message was originally an encrypted message. We want to tell the user that they can be cool about a message they are reading since that message came in encrypted.
We had that information on X-Leap-Signature for signatures, now we are adding X-Leap-Encryption for encryption stats.
If the header isn't there you can assume the message came in as plain text.
All feedback is more than welcome :)
Thanks,
Duda/Bruno.

When message is decrypted in IncomingMail, add decrypted header to it

---

changes/bug-7480_extract_attach_and_openpgp
src/leap/mail/incoming/service.py
src/leap/mail/incoming/tests/test_incoming_mail.py
src/leap/mail/tests/__init__.py

The key extracto should check first for attached keys and if this fails
then should try the OpenPGP header.
- Resolves: #7480

[bug] don't extract openpgp header if valid attached key

---

src/leap/mail/mail.py
src/leap/mail/outgoing/service.py
src/leap/mail/smtp/gateway.py

As a class variable multiple account instances share
mailboxes which is bad if its different users or tests
This problem also made the tests flaky, the sometimes failed for a hard to detect reason - mails from previous tests remained.

[bug] Make _collection_mapping a instance variable

---

changes/bug-7430_signal_InvalidAuthTokenError
src/leap/mail/incoming/service.py

In case of InvalidAuthTokeError from soledad sync we need signal the GUI, so
it will request her to log in again.
- Resolves: #7430

[bug] signal expired auth token to the GUI

---

src/leap/mail/imap/mailbox.py
src/leap/mail/imap/server.py

we were adding listeners for each mailbox instance, which was making
appends particularly slow, since the method that gets current count and
recent count is expensive and was being called way too many times.

[bug] fix slow appends

---

changes/next-changelog.rst
src/leap/mail/imap/account.py
src/leap/mail/imap/server.py
src/leap/mail/imap/service/imap-server.tac
src/leap/mail/imap/service/imap.py
src/leap/mail/imap/tests/test_imap.py
src/leap/mail/imap/tests/utils.py
src/leap/mail/outgoing/service.py
src/leap/mail/smtp/gateway.py

==Work in progress.==
This will be needed to try the latest bonafide/bitmask.core stuff.
This will also need some adjustments in the current initialization in the bitmask client.

[feat] credentials handling: use twisted.cred

---

pkg/requirements-latest.pip
src/leap/mail/generator.py
src/leap/mail/tests/__init__.py

- leap_mail still uses pycryptopp and therefore still needs the
dependency
- Keymanager calls to async HTTPClient had not been mocked, causing
a test to fail
- fixed a pep8 warning

[tests] fix missing pycryptopp dependency and mock async calls

---

src/leap/mail/walk.py

for some reason, available_backends does not work inside a frozen
PyInstaller binary.
- Resolves: #7952

[bug] specify openssl backend explicitely

---

src/leap/mail/imap/service/imap.py
src/leap/mail/smtp/gateway.py

This greatly simplifies the handling of the password in the thunderbird
extension.
Related: #6041

[feature] use same token for imap/stmp authentication

---

MANIFEST.in
setup.py

The name of the `CHANGELOG` file was changed some weeks ago to `CHANGELOG.rst` but the `setup.py` script was not changed accordingly.

[bug] fix CHANGELOG.rst open in setup.py

---

changes/next-changelog.rst
src/leap/mail/outgoing/service.py

This fixes a bug in which the tls transport complains about receiving
unicode. It was only made evident by running against twisted 16.

[bug] cast the identity to bytes

---

changes/next-changelog.rst
src/leap/mail/imap/mailbox.py

One of the pixelated adaptors was trying to access a non-existing
attribute in HashableMailbox, which for some reason was blocking the
operation of the imap server (uncatched exception in listeners call
maybe).
adding an attribute skips this error and therefore allows seamless use
of both pixelated and thunderbird user agents at the same time.
Resolves: #8083

[bug] Allow pixelated integration not to interfere with thunderbird

---

src/leap/mail/incoming/tests/test_incoming_mail.py

The functions decryption_error_not_called and add_decrypted_header_called
were not being called on testDecryptEmail. So the asserts was not being
called as well.
This change adds the above functions as callbacks to be called after the
fetch method.

Add not called asserts to testDecryptEmail

---

src/leap/mail/incoming/service.py
src/leap/mail/incoming/tests/rfc822.multi-encrypt-signed.message
src/leap/mail/incoming/tests/test_incoming_mail.py

**Disclaimer:**
As we previously talked with @kalikaneko and @jeffhsta we think could be easier to open a new pull request to fix this bug because the previous one (https://github.com/leapcode/leap_mail/pull/225) got pretty outdated. When this PR be accept the old one can be closed.
**Context:**
Leap mail has a step that uses keymanager to decrypt an email and at the same time it validates signature. It works well when the incoming email was created using Thunderbird, but when using Apple Mail that step is not enough because the way Apple Mail encrypt and sign the email. While Thunderbird does something like `gpg -se [message]` to encrypt and sign an email, Apple Mail first sign the message and only after it encrypt the previous signed message. Something like that `gpg -s [message] | gpg …

Fix signature validation on encrypted email from Apple Mail

---

pkg/requirements-latest.pip

Since our copies of leap are now in sync with leap,
we don't have to install our forks anymore.
And it was always strange that leap_mail had 
references to pixelated.
See https://github.com/pixelated/puppet-pixelated/issues/49

remove links to pixelated
